"""
Shared test fixtures for all test modules.
Generated by: test-generator agent (TDD RED phase)
Jira: PROJ-1 — GET country capital API
"""
from typing import List, Tuple

import pytest
from fastapi.testclient import TestClient

from src.main import app


@pytest.fixture(scope="module")
def client() -> TestClient:
    """FastAPI test client — use for all integration tests."""
    return TestClient(app)


@pytest.fixture
def valid_countries() -> List[Tuple[str, str]]:
    """Sample of valid country → capital pairs for parametrized tests."""
    return [
        ("France", "Paris"),
        ("Germany", "Berlin"),
        ("Japan", "Tokyo"),
        ("Brazil", "Brasília"),
        ("India", "New Delhi"),
        ("Australia", "Canberra"),
        ("Canada", "Ottawa"),
        ("Mexico", "Mexico City"),
        ("Italy", "Rome"),
        ("Spain", "Madrid"),
        ("United Kingdom", "London"),
        ("United States", "Washington, D.C."),
        ("China", "Beijing"),
        ("Russia", "Moscow"),
        ("South Africa", "Pretoria"),
    ]


@pytest.fixture
def invalid_inputs() -> List[str]:
    """Inputs that should result in 400 Bad Request."""
    return [
        "",
        "   ",
        "123",
        "!!!",
        "@#$%",
    ]
